---
galaxy_info:
  role_name: rabbitmq
  author: rockandska
  description: RabbitMQ (HA compatible)
  company: none
  license: BSD
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - stretch
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - erlang
    - rabbitmq

dependencies: []
