---
- name: "[RabbitMQ] Add RabbitMQ repository file [RHEL/CentOS]"
  template:
    src: "{{ rabbitmq_rpm_repo_tpl }}"
    dest: "/etc/yum.repos.d/{{ rabbitmq_rpm_repo_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    mode: 0644
    backup: true

- name: "[RabbitMQ] Install RabbitMQ [RHEL/CentOS]"
  yum:
    name: "rabbitmq-server{{ rabbitmq_series_rpm_version | ternary ('-' + (rabbitmq_series_rpm_version | string),'-' + (rabbitmq_series | string) + '*') }}"
    state: present
    disablerepo: "{{ rabbitmq_rpm_disable_repo | d(omit, true) }}"
    enablerepo: "{{ rabbitmq_rpm_enable_repo | d(omit, true) }}"
