---
- name: "[RabbitMQ] Creation of vhosts"
  rabbitmq_vhost:
    name: "{{ item.name }}"
    tracing: "{{ item.tracing | default(omit) }}"
    state: present
    node: "{{ rabbitmq_node_name | default(omit,true) }}"
  with_items:
    - "{{ rabbitmq_vhosts_to_create }}"
  when:
    - rabbitmq_is_master
      or rabbitmq_slave_of is none

- name: "[RabbitMQ] Remove unwanted vhosts"
  rabbitmq_vhost:
    name: "{{ item }}"
    state: absent
    node: "{{ rabbitmq_node_name | default(omit,true) }}"
  with_items:
    - "{{ rabbitmq_vhosts_to_delete }}"
  when:
    - rabbitmq_is_master
      or rabbitmq_slave_of is none
